apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The 'namespace' field is updated automatically by the Makefile file
# Use OCP_NAMESPACE env variable for changing this
namespace: freeipa

# bases:
#   - ../base

resources:
- common/
- pod-main.yaml

# generators:
#   - 

# transformers:
#   -

configurations:
- kustomizeconfig.yaml
