---
# nameReference:
#   - kind: Service
#     version: v1
#     fieldSpecs:
#       - kind: CustomResourceDefinition
#         group: apiextensions.k8s.io
#         path: spec/conversion/webhookClientConfig/service/name

# varReference:
#   - path: metadata/annotations
#   - kind: IDM
#     path: spec/passwordSecret

varReference:
  - kind: StatefulSet
    path: spec/template/spec/containers/args

images:
  - name: main
    newName: quay.io/freeipa/freeipa-openshift-container
    newTag: freeipa-server
