apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: freeipa

resources:
- ../../single-pod/common/
- statefulset.yaml

# generators:
#   - 

# transformers:
#   -

# vars:
  # - name: IPA_SERVER_HOSTNAME
  #   objref:
  #     name: config
  #     kind: ConfigMap
  #     apiVersion: v1
  #   fieldref:
  #     fieldpath: data.IPA_SERVER_HOSTNAME
  # - name: IPA_SERVER_REALM
  #   objref:
  #     name: config
  #     kind: ConfigMap
  #     apiVersion: v1
  #   fieldref:
  #     fieldpath: data.IPA_SERVER_REALM
  # - name: IPA_SERVER_CA_SUBJECT
  #   objref:
  #     name: config
  #     kind: ConfigMap
  #     apiVersion: v1
  #   fieldref:
  #     fieldpath: data.IPA_SERVER_CA_SUBJECT

configurations:
- kustomizeconfig.yaml
